#pragma once
#include <cstdint>
namespace EMapLocTypes {
#pragma pack(push, 1)
enum Type : uint8_t {
    MAP_LOC_KEY_NONE = 0,
    MAP_LOC_KEY_ZOOM = 1,
    MAP_LOC_KEY_NEXT_MAP = 2,
    MAP_LOC_KEY_TRACK_QUEST = 3,
    MAP_LOC_KEY_UNTRACK_QUEST = 4,
    MAP_LOC_KEY_SET_WAYPOINT = 5,
    MAP_LOC_KEY_UNSET_WAYPOINT = 6,
    MAP_LOC_KEY_TRAVEL = 7,
    MAP_LOC_KEY_TRAVEL_CLOSEST = 8,
    MAP_LOC_KEY_BACK = 9,
    MAP_LOC_KEY_SELECT = 10,
    MAP_LOC_KEY_MOVE_CAMERA = 11,
    MAP_LOC_KEY_FILTER = 12,
    MAP_LOC_KEY_ROTATE = 13,
    MAP_LOC_GOTO_QUEST_LOG = 14,
    MAP_LOC_GOTO_QUEST_LOG_MNK = 15,
    MAP_LOC_KEY_FAST_TRAVEL_LIST_DO_FAST_TRAVEL = 16,
    MAP_LOC_KEY_FAST_TRAVEL_LIST_DO_SELECT_REGION = 17,
    MAP_LOC_KEY_WAIT = 18,
    MAP_LOC_KEY_TRAVEL_MOUSE_KBD = 19,
    MAP_LOC_KEY_ROTATE_MOUSE_KBD = 20,
    MAP_LOC_KEY_FAST_TRAVEL_LIST_DO_FAST_TRAVEL_MOUSE_KBD = 21,
    MAP_LOC_MAX = 22,
};
#pragma pack(pop)
}
