#pragma once
#include <cstdint>
#pragma pack(push, 1)
enum ActivityTypeIDs : uint8_t {
    ACTIVITY_TYPE_CLASS = 0,
    ACTIVITY_TYPE_CLUB = 1,
    ACTIVITY_TYPE_COMPANION = 2,
    ACTIVITY_TYPE_EVENT = 3,
    ACTIVITY_TYPE_EXCURSION = 4,
    ACTIVITY_TYPE_FREETIME = 5,
    ACTIVITY_TYPE_GUARD = 6,
    ACTIVITY_TYPE_INVESTIGATE = 7,
    ACTIVITY_TYPE_MEAL = 8,
    ACTIVITY_TYPE_MINGLE = 9,
    ACTIVITY_TYPE_MISSION = 10,
    ACTIVITY_TYPE_MISSIONCRITICAL = 11,
    ACTIVITY_TYPE_NURTURE = 12,
    ACTIVITY_TYPE_OCCUPATION = 13,
    ACTIVITY_TYPE_PATROL = 14,
    ACTIVITY_TYPE_PERFORMTASK = 15,
    ACTIVITY_TYPE_REST = 16,
    ACTIVITY_TYPE_SEATFILLERSTATIC = 17,
    ACTIVITY_TYPE_SELFSTUDY = 18,
    ACTIVITY_TYPE_SLEEP = 19,
    ACTIVITY_TYPE_TRANSIENTACTION = 20,
    ACTIVITY_TYPE_COUNT = 21,
    ACTIVITY_TYPE_MAX = 22,
};
#pragma pack(pop)
