#pragma once
#include <cstdint>
#pragma pack(push, 1)
enum CollisionTypeIDs : uint8_t {
    STATION_COLLISION_GROUND = 0,
    STATION_COLLISION_MOVING = 1,
    STATION_COLLISION_SEATED = 2,
    STATION_COLLISION_STANDING = 3,
    STATION_COLLISION_STANDINGNOFORWARD = 4,
    STATION_COLLISION_STANDINGNOFORWARD2P = 5,
    STATION_COLLISION_STANDINGNOREVERSE = 6,
    STATION_COLLISION_STANDINGWITHPROP = 7,
    STATION_COLLISION_COUNT = 8,
    STATION_COLLISION_MAX = 9,
};
#pragma pack(pop)
