#pragma once
#include <cstdint>
#pragma pack(push, 1)
enum EAccessibilityAudioCueEventType : uint8_t {
    ACCESSIBILITY_EVENT_TYPE_INTERACT = 0,
    ACCESSIBILITY_EVENT_TYPE_FOOTSTEPS = 1,
    ACCESSIBILITY_EVENT_TYPE_SPELLCASTER = 2,
    ACCESSIBILITY_EVENT_TYPE_ALERT = 3,
    ACCESSIBILITY_EVENT_TYPE_BEAST_ROAR = 4,
    ACCESSIBILITY_EVENT_TYPE_DESTRUCTIBLE = 5,
    ACCESSIBILITY_EVENT_TYPE_RUNNING_WATER = 6,
    ACCESSIBILITY_EVENT_TYPE_DOOR_OPENCLOSE = 7,
    ACCESSIBILITY_EVENT_TYPE_SHOW_NEGATIVE_INTERACTIONS = 8,
    ACCESSIBILITY_EVENT_TYPE_BROOM = 9,
    ACCESSIBILITY_EVENT_TYPE_LOOT = 10,
    ACCESSIBILITY_EVENT_TYPE_BEAST_AWARE = 11,
    ACCESSIBILITY_EVENT_TYPE_HIT = 12,
    ACCESSIBILITY_EVENT_TYPE_AMBIENT_CONVERSATION = 13,
    ACCESSIBILITY_EVENT_TYPE_STEALTH_DETECTED = 14,
    ACCESSIBILITY_EVENT_TYPE_REVELIO_BELL = 15,
    ACCESSIBILITY_EVENT_TYPE_NONE = 16,
    ACCESSIBILITY_EVENT_TYPE_MAX = 17,
};
#pragma pack(pop)
