#pragma once
#include <cstdint>
#pragma pack(push, 1)
enum class EBeaconState : uint8_t {
    BEACONSTATE_NONE = 0,
    BEACONSTATE_HIDDEN_BY_FOG_OF_WAR = 1,
    BEACONSTATE_UNDISCOVERED_HIDDEN = 2,
    BEACONSTATE_UNDISCOVERED = 3,
    BEACONSTATE_DISCOVERED = 4,
    BEACONSTATE_DISCOVERED_INCOMPLETE = 5,
    BEACONSTATE_DISCOVERED_LOCKED = 6,
    BEACONSTATE_DISCOVERED_UNLOCKED = 7,
    BEACONSTATE_FAST_TRAVEL_LOCKED = 8,
    BEACONSTATE_FAST_TRAVEL_UNLOCKED = 9,
    BEACONSTATE_HANDLED_AT_RUNTIME = 10,
    BEACONSTATE_COMPLETED = 11,
    BEACONSTATE_MISSION_LEVEL_NOT_ENOUGH = 12,
    BEACONSTATE_VENDOR_ACTIVE = 13,
    BEACONSTATE_VENDOR_INACTIVE = 14,
    BEACONSTATE_ICON_STACK = 15,
    BEACONSTATE_MAX = 16,
};
#pragma pack(pop)
