#pragma once
#include <cstdint>
#pragma pack(push, 1)
enum class EBeaconFlags {
    BEACON_FLAG_NONE = 0,
    BEACON_FLAG_HIDEINACTIVE = 1,
    BEACON_FLAG_SHOWINWORLD = 2,
    BEACON_FLAG_FORCESTATIC = 4,
    BEACON_FLAG_FORCEINACTIVE = 8,
    BEACON_FLAG_ALWAYSCOMPASS = 16,
    BEACON_FLAG_HIDEDISTANCEONHUD = 32,
    BEACON_FLAG_DONTLOCKONHUD = 64,
    BEACON_FLAG_HIDEFROMMAP = 128,
    BEACON_FLAG_ALL = 255,
    BEACON_FLAG_MAX = 256,
};
#pragma pack(pop)
