#pragma once
#include <cstdint>
#pragma pack(push, 1)
enum class EBeaconSubType : uint8_t {
    BEACONSUBTYPE_NONE = 0,
    BEACONSUBTYPE_CHEST_DEFAULT = 1,
    BEACONSUBTYPE_CHEST_TRACKED = 2,
    BEACONSUBTYPE_CHEST_LOOTABLE = 3,
    BEACONSUBTYPE_BEASTDEN_DIRICAWL = 4,
    BEACONSUBTYPE_BEASTDEN_FWOOPER = 5,
    BEACONSUBTYPE_BEASTDEN_GIANTPURPLETOAD = 6,
    BEACONSUBTYPE_BEASTDEN_GRAPHORN = 7,
    BEACONSUBTYPE_BEASTDEN_HIPPOGRIFF = 8,
    BEACONSUBTYPE_BEASTDEN_JOBBERKNOLL = 9,
    BEACONSUBTYPE_BEASTDEN_KNEAZLE = 10,
    BEACONSUBTYPE_BEASTDEN_MOONCALF = 11,
    BEACONSUBTYPE_BEASTDEN_NIFFLER = 12,
    BEACONSUBTYPE_BEASTDEN_PUFFSKEIN = 13,
    BEACONSUBTYPE_BEASTDEN_THESTRAL = 14,
    BEACONSUBTYPE_BEASTDEN_UNICORN = 15,
    BEACONSUBTYPE_COMBATCHALLENGE_PLAYSTATION = 16,
    BEACONSUBTYPE_MAX = 17,
};
#pragma pack(pop)
