#pragma once
#include <cstdint>
#pragma pack(push, 1)
enum class EEnemyAIAnimState : uint8_t {
    Idle = 0,
    IdleReady = 1,
    Moving = 2,
    Spawn = 3,
    Attack = 4,
    BecomeAware = 5,
    LoseAware = 6,
    ActivateStoredWeapon = 7,
    StoreActiveWeapon = 8,
    PickupWeaponFloor = 9,
    PickupWeaponWall = 10,
    PickupWeapon = 11,
    DodgeLeft = 12,
    DodgeRight = 13,
    Dodge = 14,
    Disappear_DEPRECATED = 15,
    Reappear_DEPRECATED = 16,
    Taunt = 17,
    Land = 18,
    TurnInPlace = 19,
    Shuffle = 20,
    FleeExit = 21,
    MovingRunTo = 22,
    React = 23,
    NurtureInteract_DEPRECATED = 24,
    Eat_DEPRECATED = 25,
    Jump = 26,
    Dead = 27,
    Climb = 28,
    IdleBreak = 29,
    BecomeAlert = 30,
    LoseAlert = 31,
    Apparate = 32,
    Flourish = 33,
    Flying = 34,
    StartDrained = 35,
    StopDrained = 36,
    Drained = 37,
    AlertWait = 38,
    AlertLook = 39,
    JumpSpline = 40,
    EEnemyAIAnimState_MAX = 41,
};
#pragma pack(pop)
