#pragma once
#include <cstdint>
#pragma pack(push, 1)
enum class EEnemy_AttackUpdateState : uint8_t {
    None = 0,
    Init = 1,
    Moving = 2,
    Paused = 3,
    StartFace = 4,
    Face = 5,
    StopMove = 6,
    StoppingMove = 7,
    Taunt = 8,
    Shuffle = 9,
    Attack = 10,
    TauntAttack = 11,
    Cover = 12,
    StartReady = 13,
    PickupWeapon = 14,
    StoreActiveWeapon = 15,
    FaceWeapon = 16,
    Ready = 17,
    Apperate = 18,
    CheckRetreat = 19,
    FaceLoc = 20,
    Stunned = 21,
    Jump = 22,
    IdleBreak = 23,
    StartMove = 24,
    UpdateMove = 25,
    StartAttack = 26,
    StartRetreat = 27,
    StopRetreat = 28,
    Retreating = 29,
    StoppingRetreat = 30,
    Flourish = 31,
    Protego = 32,
    StartDrained = 33,
    Drained = 34,
    StopDrained = 35,
    Equip = 36,
    CounterAttack = 37,
    StartMoveWait = 38,
    Count = 39,
    EEnemy_MAX = 40,
};
#pragma pack(pop)
