#pragma once
#include <cstdint>
#pragma pack(push, 1)
enum EFieldGuideExitReasons : uint8_t {
    FIELD_GUIDE_EXIT_REASON_NONE = 0,
    FIELD_GUIDE_EXIT_REASON_BACK_TO_GAME = 1,
    FIELD_GUIDE_EXIT_REASON_BACK_TO_GAME_FROM_MAP = 2,
    FIELD_GUIDE_EXIT_REASON_LOAD_GAME = 3,
    FIELD_GUIDE_EXIT_REASON_RESTART_FROM_LAST_SAVE = 4,
    FIELD_GUIDE_EXIT_REASON_EXIT_TO_MAIN = 5,
    FIELD_GUIDE_EXIT_REASON_EXIT_TO_MAIN_GAME_OVER = 6,
    FIELD_GUIDE_EXIT_REASON_QUIT_GAME = 7,
    FIELD_GUIDE_EXIT_REASON_FAST_TRAVEL_FROM_MAP = 8,
    FIELD_GUIDE_EXIT_REASON_HOVER_DRONE = 9,
    FIELD_GUIDE_EXIT_REASON_FAST_TRAVEL_FROM_IMGUI = 10,
    FIELD_GUIDE_EXIT_REASON_ABANDON_QUEST_FROM_QUEST_LOG = 11,
    FIELD_GUIDE_EXIT_REASON_ABANDON_QUEST_FROM_GAME_OVER = 12,
    FIELD_GUIDE_EXIT_REASON_MAX = 13,
};
#pragma pack(pop)
