#pragma once
#include <cstdint>
#pragma pack(push, 1)
enum EFieldGuideExitStates {
    FIELD_GUIDE_EXIT_STATE_NONE = 0,
    FIELD_GUIDE_EXIT_STATE_FADING_IN = 1,
    FIELD_GUIDE_EXIT_STATE_FADING_OUT = 2,
    FIELD_GUIDE_EXIT_STATE_SPIN_ON_BLANK = 3,
    FIELD_GUIDE_EXIT_STATE_DELAY = 4,
    FIELD_GUIDE_EXIT_STATE_UNLOAD_FIELD_GUIDE = 5,
    FIELD_GUIDE_EXIT_STATE_NO_FADE = 6,
    FIELD_GUIDE_EXIT_STATE_RESTART_FROM_LAST_SAVE = 7,
    FIELD_GUIDE_EXIT_STATE_LOAD_GAME = 8,
    FIELD_GUIDE_EXIT_STATE_EXIT_TO_MAIN = 9,
    FIELD_GUIDE_EXIT_STATE_EXIT_TO_MAIN_GAME_OVER = 10,
    FIELD_GUIDE_EXIT_STATE_HOVER_DRONE = 11,
    FIELD_GUIDE_EXIT_STATE_FAST_TRAVEL_FROM_MAP = 12,
    FIELD_GUIDE_EXIT_STATE_FAST_TRAVEL_FROM_IMGUI = 13,
    FIELD_GUIDE_EXIT_STATE_ABANDON_QUEST_FROM_QUEST_LOG = 14,
    FIELD_GUIDE_EXIT_STATE_ABANDON_QUEST_FROM_GAME_OVER = 15,
    FIELD_GUIDE_EXIT_STATE_HOLD_FADE = 16,
    FIELD_GUIDE_EXIT_STATE_MAX = 17,
};
#pragma pack(pop)
