#pragma once
#include <cstdint>
#pragma pack(push, 1)
enum EHomeworkType : uint8_t {
    HOMEWORK_TYPE_SPELL_CAST = 0,
    HOMEWORK_TYPE_SPELL_SUCCESS = 1,
    HOMEWORK_TYPE_POTION = 2,
    HOMEWORK_TYPE_POTION_CONSUMED = 3,
    HOMEWORK_TYPE_SANCTUARY_USE = 4,
    HOMEWORK_TYPE_PLANT = 5,
    HOMEWORK_TYPE_BEAST = 6,
    HOMEWORK_TYPE_COMPANION_MINUTES = 7,
    HOMEWORK_TYPE_BROOM = 8,
    HOMEWORK_TYPE_COMBAT = 9,
    HOMEWORK_TYPE_COLLECT = 10,
    HOMEWORK_TYPE_INVESTIGATE = 11,
    HOMEWORK_TYPE_MISC = 12,
    HOMEWORK_TYPE_CONJURATION = 13,
    HOMEWORK_TYPE_COUNT = 14,
    HOMEWORK_TYPE_MAX = 15,
};
#pragma pack(pop)
