#pragma once
#include <cstdint>
#pragma pack(push, 1)
enum class EInteractiveState : uint8_t {
    Normal = 0,
    Any = 1,
    Locked = 2,
    Unlocked = 3,
    Open = 4,
    Closed = 5,
    Frozen = 6,
    Wet = 7,
    OnFire = 8,
    Invisible = 9,
    Immobilized = 10,
    ScaleIncreased = 11,
    ScaledDecreased = 12,
    MassIncreased = 13,
    MassDecreased = 14,
    Undamaged = 15,
    Damage_1 = 16,
    Damage_2 = 17,
    Damage_3 = 18,
    Destroyed = 19,
    Cut = 20,
    Custom_1 = 21,
    Custom_2 = 22,
    Custom_3 = 23,
    Custom_4 = 24,
    Custom_5 = 25,
    Custom_6 = 26,
    Custom_7 = 27,
    Custom_8 = 28,
    Custom_9 = 29,
    Failed = 30,
    Highlighted = 31,
    Dead = 32,
    Unsolved = 33,
    Solved = 34,
    Harvested = 35,
    StateCount = 36,
    None = 255,
};
#pragma pack(pop)
