#pragma once
#include <cstdint>
#pragma pack(push, 1)
enum class EInventoryChangeReason : uint8_t {
    INVENTORY_CHANGE_REASON_GENERIC = 0,
    INVENTORY_CHANGE_REASON_SOLD = 1,
    INVENTORY_CHANGE_REASON_STOLEN = 2,
    INVENTORY_CHANGE_REASON_PLANTED = 3,
    INVENTORY_CHANGE_REASON_CONSOLE_DEBUG = 4,
    INVENTORY_CHANGE_REASON_POPULATE_VENDOR = 5,
    INVENTORY_CHANGE_REASON_TRANSFERRED = 6,
    INVENTORY_CHANGE_REASON_DROPPED = 7,
    INVENTORY_CHANGE_REASON_GIFTED = 8,
    INVENTORY_CHANGE_REASON_ACTIVITY = 9,
    INVENTORY_CHANGE_REASON_CURRICULUM = 10,
    INVENTORY_CHANGE_REASON_LOOT = 11,
    INVENTORY_CHANGE_REASON_MAIL = 12,
    INVENTORY_CHANGE_REASON_MISSION = 13,
    INVENTORY_CHANGE_REASON_CREATURES = 14,
    INVENTORY_CHANGE_REASON_CRIME = 15,
    INVENTORY_CHANGE_REASON_HERBOLOGY = 16,
    INVENTORY_CHANGE_REASON_POTION_BREW = 17,
    INVENTORY_CHANGE_REASON_CONVERTER = 18,
    INVENTORY_CHANGE_REASON_CONJURATION = 19,
    INVENTORY_CHANGE_REASON_USED = 20,
    INVENTORY_CHANGE_REASON_FORAGED = 21,
    INVENTORY_CHANGE_REASON_PURCHASE = 22,
    INVENTORY_CHANGE_REASON_GEAR_TRANSFER = 23,
    INVENTORY_CHANGE_REASON_MAX = 24,
};
#pragma pack(pop)
