#pragma once
#include <cstdint>
#pragma pack(push, 1)
enum EKnowledgeAction : uint8_t {
    AstronomyAltar = 0,
    BeastCaptured = 1,
    BreedingAssigned = 2,
    BrewPotion = 3,
    CalloutReference = 4,
    Collect = 5,
    Conjure = 6,
    ConversationReference = 7,
    ConversationReward = 8,
    CraftTrait = 9,
    Damaged = 10,
    DemiguiseStatue = 11,
    Discover = 12,
    DuelTechniqueCompleted = 13,
    GatherBeastByproduct = 14,
    GatherPlant = 15,
    HappinessFromFeed = 16,
    HappinessFromPetting = 17,
    HappinessFromPlaying = 18,
    Interact = 19,
    Investigation = 20,
    Killed = 21,
    Mission = 22,
    MissionDayOne = 23,
    MissionJumbo = 24,
    MissionLarge = 25,
    MissionMedium = 26,
    MissionSmall = 27,
    Perceived = 28,
    Received = 29,
    SocialConversation = 30,
    SocialGiveGift = 31,
    SpellCast = 32,
    TutorialUnlock = 33,
    UseFertilizer = 34,
    NamedEnemyKilled = 35,
    HouseChestOpened = 36,
    GoldChestOpened = 37,
    AncientMagicHotSpot = 38,
    MerlinTrialCompleted = 39,
    RecipeLearned = 40,
    UpgradeStats = 41,
    EKnowledgeAction_MAX = 42,
};
#pragma pack(pop)
