#pragma once
#include <cstdint>
#pragma pack(push, 1)
enum EMapStackedIconState {
    MAP_STACKED_ICON_STATE_NONE = 0,
    MAP_STACKED_ICON_STATE_IS_HOVERED = 1,
    MAP_STACKED_ICON_STATE_TRIGGER_CHOOSER = 2,
    MAP_STACKED_ICON_STATE_ANIMATE_CHOOSER = 3,
    MAP_STACKED_ICON_STATE_ANIMATE_CHOOSER_REVERSE = 4,
    MAP_STACKED_ICON_STATE_IN_CHOOSER = 5,
    MAP_STACKED_ICON_STATE_MAX = 6,
};
#pragma pack(pop)
