#pragma once
#include <cstdint>
#pragma pack(push, 1)
enum EMapIconInstanceTextureType {
    MAP_ICON_INSTANCE_TEXTURE_TYPE_TEXTURE = 0,
    MAP_ICON_INSTANCE_TEXTURE_TYPE_DOT = 1,
    MAP_ICON_INSTANCE_TEXTURE_TYPE_DIAMOND = 2,
    MAP_ICON_INSTANCE_TEXTURE_TYPE_QUESTIONMARK = 3,
    MAP_ICON_INSTANCE_TEXTURE_TYPE_ALTERNATE = 4,
    MAP_ICON_INSTANCE_TEXTURE_TYPE_INVALID = 5,
    MAP_ICON_INSTANCE_TEXTURE_TYPE_MAX = 6,
};
#pragma pack(pop)
