#pragma once
#include <cstdint>
#pragma pack(push, 1)
enum class EMapToolTipTypes : uint8_t {
    MAP_TOOL_TIP_TYPE_UNSET = 0,
    MAP_TOOL_TIP_TYPE_DUNGEON = 1,
    MAP_TOOL_TIP_TYPE_FAST_TRAVEL = 2,
    MAP_TOOL_TIP_TYPE_CASTLE = 3,
    MAP_TOOL_TIP_TYPE_HAMLET = 4,
    MAP_TOOL_TIP_TYPE_BANDIT_CAMP = 5,
    MAP_TOOL_TIP_TYPE_WAY_MARKER = 6,
    MAP_TOOL_TIP_TYPE_PLAYER_MARKER = 7,
    MAP_TOOL_TIP_TYPE_FILTER_REGION = 8,
    MAP_TOOL_TIP_TYPE_HOGWARTS = 9,
    MAP_TOOL_TIP_TYPE_HOGSMEADE = 10,
    MAP_TOOL_TIP_TYPE_ENEMY_LOCATION = 11,
    MAP_TOOL_TIP_TYPE_MISSION = 12,
    MAP_TOOL_TIP_TYPE_STACK = 13,
    MAP_TOOL_TIP_TYPE_MAX = 14,
};
#pragma pack(pop)
