#pragma once
#include <cstdint>
#pragma pack(push, 1)
enum EMapFadeState : uint8_t {
    MAP_FADE_STATE_IDLE = 0,
    MAP_FADE_STATE_FADING_OUT = 1,
    MAP_FADE_STATE_FADING_IN = 2,
    MAP_FADE_STATE_FADING_TRANSITION = 3,
    MAP_FADE_STATE_ZOOMING_IN = 4,
    MAP_FADE_STATE_ZOOMING_OUT = 5,
    MAP_FADE_STATE_FADED_OUT = 6,
    MAP_FADE_SCREEN_WIDGET_IN = 7,
    MAP_FADE_SCREEN_WIDGET_OUT = 8,
    MAP_FADE_TENT_FADING_OUT = 9,
    MAP_FADE_TENT_FADING_IN = 10,
    MAP_FADE_TENT_WAITING = 11,
    MAP_WIDGET_STATE_FADING_OUT = 12,
    MAP_WIDGET_STATE_FADING_IN = 13,
    MAP_FADE_STATE_PULSE = 14,
    MAP_MAX = 15,
};
#pragma pack(pop)
