#pragma once
#include <cstdint>
#pragma pack(push, 1)
enum EMiniMapTextureQuadrant {
    MINIMAP_TEXTURE_QUADRANT_LEFT = 0,
    MINIMAP_TEXTURE_QUADRANT_RIGHT = 1,
    MINIMAP_TEXTURE_QUADRANT_TOP = 2,
    MINIMAP_TEXTURE_QUADRANT_BOTTOM = 3,
    MINIMAP_TEXTURE_QUADRANT_TOP_RIGHT = 4,
    MINIMAP_TEXTURE_QUADRANT_BOTTOM_LEFT = 5,
    MINIMAP_TEXTURE_QUADRANT_TOP_LEFT = 6,
    MINIMAP_TEXTURE_QUADRANT_BOTTOM_RIGHT = 7,
    MINIMAP_TEXTURE_QUADRANT_MAX = 8,
};
#pragma pack(pop)
