#pragma once
#include <cstdint>
#pragma pack(push, 1)
enum class EMultiFXLoc : uint8_t {
    Location = 0,
    Location_Attached = 1,
    Location_ObjectOrient = 2,
    Location_ObjectOrient_Attached = 3,
    Location_ZeroOrient = 4,
    Location_ZeroOrient_Attached = 5,
    ObjectCenterLoc = 6,
    ObjectCenterLoc_Attached = 7,
    ObjectCenterLoc_ObjectOrient = 8,
    ObjectCenterLoc_ObjectOrient_Attached = 9,
    ObjectCenterLoc_ZeroOrient = 10,
    ObjectCenterLoc_ZeroOrient_Attached = 11,
    ObjectBottomLoc = 12,
    ObjectBottomLoc_Attached = 13,
    ObjectBottomLoc_ObjectOrient = 14,
    ObjectBottomLoc_ObjectOrient_Attached = 15,
    ObjectBottomLoc_ZeroOrient = 16,
    ObjectBottomLoc_ZeroOrient_Attached = 17,
    ObjectAnchorLoc = 18,
    ObjectAnchorLoc_Attached = 19,
    ObjectAnchorLoc_ObjectOrient = 20,
    ObjectAnchorLoc_ObjectOrient_Attached = 21,
    ObjectAnchorLoc_ZeroOrient = 22,
    ObjectAnchorLoc_ZeroOrient_Attached = 23,
    BoneLocation = 24,
    BoneLocation_Attached = 25,
    GroundBelowLoc = 26,
    GroundBelowLoc_ObjectOrient = 27,
    GroundBelowLoc_ZeroOrient = 28,
    GroundBelowLoc_NormalOrient = 29,
    GroundBelowCenterLoc = 30,
    GroundBelowCenterLoc_ObjectOrient = 31,
    GroundBelowCenterLoc_ZeroOrient = 32,
    GroundBelowCenterLoc_NormalOrient = 33,
    Wandtip_Attached = 34,
    EMultiFXLoc_MAX = 35,
};
#pragma pack(pop)
