#pragma once
#include <cstdint>
#pragma pack(push, 1)
enum class EPostProcessingVarColor : uint8_t {
    None = 0,
    FilmWhitePoint = 1,
    FilmShadowTint = 2,
    FilmChannelMixerRed = 3,
    FilmChannelMixerGreen = 4,
    FilmChannelMixerBlue = 5,
    SceneColorTint = 6,
    Bloom1Tint = 7,
    Bloom2Tint = 8,
    Bloom3Tint = 9,
    Bloom4Tint = 10,
    Bloom5Tint = 11,
    Bloom6Tint = 12,
    BloomDirtMaskTint = 13,
    AmbientCubemapTint = 14,
    LensFlareTint = 15,
    IndirectLightingColor = 16,
    ColorSaturation = 17,
    ColorContrast = 18,
    ColorGamma = 19,
    ColorGain = 20,
    ColorOffset = 21,
    ColorSaturationShadows = 22,
    ColorContrastShadows = 23,
    ColorGammaShadows = 24,
    ColorGainShadows = 25,
    ColorOffsetShadows = 26,
    ColorSaturationMidtones = 27,
    ColorContrastMidtones = 28,
    ColorGammaMidtones = 29,
    ColorGainMidtones = 30,
    ColorOffsetMidtones = 31,
    ColorSaturationHighlights = 32,
    ColorContrastHighlights = 33,
    ColorGammaHighlights = 34,
    ColorGainHighlights = 35,
    ColorOffsetHighlights = 36,
    ReflectionCaptureOutsideColorTint = 37,
    ReflectionCaptureInsideColorTint = 38,
    EPostProcessingVarColor_MAX = 39,
};
#pragma pack(pop)
