#pragma once
#include <cstdint>
#pragma pack(push, 1)
enum class EUpscaleMode : uint8_t {
    None = 0,
    DLSS_Off = 1,
    DLSS_Auto = 2,
    DLSS_UltraPerformance = 3,
    DLSS_Performance = 4,
    DLSS_Balanced = 5,
    DLSS_Quality = 6,
    DLSS_UltraQuality = 7,
    AMD_FSR_Performance = 8,
    AMD_FSR_Balanced = 9,
    AMD_FSR_Quality = 10,
    AMD_FSR_UltraQuality = 11,
    NIS_Performance = 12,
    NIS_Balanced = 13,
    NIS_Quality = 14,
    NIS_UltraQuality = 15,
    AMD_FSR2_UltraPerformance = 16,
    AMD_FSR2_Performance = 17,
    AMD_FSR2_Balanced = 18,
    AMD_FSR2_Quality = 19,
    Intel_XeSS_Performance = 20,
    Intel_XeSS_Balanced = 21,
    Intel_XeSS_Quality = 22,
    Intel_XeSS_UltraQuality = 23,
    DLSS_Min = 1,
    DLSS_Max = 7,
    AMD_FSR_Min = 8,
    AMD_FSR_Max = 11,
    NIS_Min = 12,
    NIS_Max = 15,
    AMD_FSR2_Min = 16,
    AMD_FSR2_Max = 19,
    Intel_XeSS_Min = 20,
    Intel_XeSS_Max = 23,
    EUpscaleMode_MAX = 24,
};
#pragma pack(pop)
