#pragma once
#include <cstdint>
#pragma pack(push, 1)
enum EViewModeIndex : uint8_t {
    VMI_BrushWireframe = 0,
    VMI_Wireframe = 1,
    VMI_Unlit = 2,
    VMI_Lit = 3,
    VMI_Lit_DetailLighting = 4,
    VMI_LightingOnly = 5,
    VMI_LightComplexity = 6,
    VMI_ShaderComplexity = 8,
    VMI_LightmapDensity = 9,
    VMI_LitLightmapDensity = 10,
    VMI_ReflectionOverride = 11,
    VMI_VisualizeBuffer = 12,
    VMI_StationaryLightOverlap = 14,
    VMI_CollisionPawn = 15,
    VMI_CollisionVisibility = 16,
    VMI_LODColoration = 18,
    VMI_QuadOverdraw = 19,
    VMI_PrimitiveDistanceAccuracy = 20,
    VMI_MeshUVDensityAccuracy = 21,
    VMI_ShaderComplexityWithQuadOverdraw = 22,
    VMI_HLODColoration = 23,
    VMI_GroupLODColoration = 24,
    VMI_MaterialTextureScaleAccuracy = 25,
    VMI_RequiredTextureResolution = 26,
    VMI_PathTracing = 27,
    VMI_RayTracingDebug = 28,
    VMI_QuadOverdrawNoDepthPrepass = 29,
    VMI_ProbeCapture = 97,
    VMI_ProbeCaptureMovable = 98,
    VMI_ProbeCaptureSecondBounce = 99,
    VMI_ValidatePBRMaterials = 101,
    VMI_VisualizeBaseColorLuminance = 102,
    VMI_AVA_CollisionSlope = 103,
    VMI_WBGM_ShadowCasters = 104,
    VMI_WBGM_OpacityMask = 108,
    VMI_WBGM_TileCountRayTracing = 109,
    VMI_Max = 110,
    VMI_Unknown = 255,
};
#pragma pack(pop)
