#pragma once
#include <cstdint>
#pragma pack(push, 1)
enum class EWInstrumentedProfilerCategorySettings : uint32_t {
    NotSelected = 0,
    Always = 1,
    Able = 2,
    Actor = 3,
    AI = 4,
    Anim = 5,
    AsyncTask = 6,
    Audio = 7,
    AvaAnimation = 8,
    Blueprint = 9,
    Character = 10,
    Collision = 11,
    CoreEngine = 12,
    FileIO = 13,
    Gameplay = 14,
    GC = 15,
    IK = 16,
    ImGui = 17,
    Missions = 18,
    Modules = 19,
    MovementComponent = 20,
    Navigation = 21,
    Network = 22,
    Physics = 23,
    Player = 24,
    PSO = 25,
    Rendering = 26,
    Stall = 27,
    Streaming = 28,
    TaskGraph = 29,
    TickFunction = 30,
    UI = 31,
    UnrealLogs = 32,
    UnrealStats = 33,
    VFX = 34,
    EWInstrumentedProfilerCategorySettings_MAX = 35,
};
#pragma pack(pop)
