#pragma once
#include <cstdint>
#pragma pack(push, 1)
enum SocialCapitalStatusIDs : uint8_t {
    SOCIALCAPITAL_STATUS_STRANGER = 0,
    SOCIALCAPITAL_STATUS_HATE = 1,
    SOCIALCAPITAL_STATUS_DISLIKE = 2,
    SOCIALCAPITAL_STATUS_INDIFFERENT = 3,
    SOCIALCAPITAL_STATUS_FAMILIAR = 4,
    SOCIALCAPITAL_STATUS_CORDIAL = 5,
    SOCIALCAPITAL_STATUS_FRIENDLY = 6,
    SOCIALCAPITAL_STATUS_COMPANION = 7,
    SOCIALCAPITAL_STATUS_COUNT = 8,
    SOCIALCAPITAL_STATUS_MAX = 9,
};
#pragma pack(pop)
