#pragma once
#include <cstdint>
#pragma pack(push, 1)
enum SocialConnectionIDs : uint8_t {
    SOCIALCONNECTION_STATUS_ENEMY = 0,
    SOCIALCONNECTION_STATUS_RIVAL = 1,
    SOCIALCONNECTION_STATUS_SELF = 2,
    SOCIALCONNECTION_STATUS_FRIEND = 3,
    SOCIALCONNECTION_STATUS_FAMILY = 4,
    SOCIALCONNECTION_STATUS_LOVEINTEREST = 5,
    SOCIALCONNECTION_STATUS_BESTFRIEND = 6,
    SOCIALCONNECTION_STATUS_COUNT = 7,
    SOCIALCONNECTION_STATUS_MAX = 8,
};
#pragma pack(pop)
