#pragma once
#include <cstdint>
#pragma pack(push, 1)
enum SocialInteractionTypeIDs : uint8_t {
    SOCIAL_INTERACTION_TYPE_ICON_INTERACTTYPE_COMPANION = 0,
    SOCIAL_INTERACTION_TYPE_ICON_INTERACTTYPE_CURRICULUM = 1,
    SOCIAL_INTERACTION_TYPE_ICON_INTERACTTYPE_EXIT = 2,
    SOCIAL_INTERACTION_TYPE_ICON_INTERACTTYPE_EXTORT = 3,
    SOCIAL_INTERACTION_TYPE_ICON_INTERACTTYPE_FACTSHEET = 4,
    SOCIAL_INTERACTION_TYPE_ICON_INTERACTTYPE_FAVOR = 5,
    SOCIAL_INTERACTION_TYPE_ICON_INTERACTTYPE_GIFT = 6,
    SOCIAL_INTERACTION_TYPE_ICON_INTERACTTYPE_MISSION = 7,
    SOCIAL_INTERACTION_TYPE_ICON_INTERACTTYPE_RELATIONSHIP = 8,
    SOCIAL_INTERACTION_TYPE_ICON_INTERACTTYPE_SANCEXPANSION = 9,
    SOCIAL_INTERACTION_TYPE_ICON_INTERACTTYPE_SCAVENGERHUNT = 10,
    SOCIAL_INTERACTION_TYPE_ICON_INTERACTTYPE_TEAGUEINVENTORY = 11,
    SOCIAL_INTERACTION_TYPE_ICON_INTERACTTYPE_VENDOR = 12,
    SOCIAL_INTERACTION_TYPE_NONE = 13,
    SOCIAL_INTERACTION_TYPE_COUNT = 14,
    SOCIAL_INTERACTION_TYPE_MAX = 15,
};
#pragma pack(pop)
