#include "ETransitionType.hpp"
#include "FClassRedirect.hpp"
#include "FColor.hpp"
#include "FDirectoryPath.hpp"
#include "FDropNoteInfo.hpp"
#include "FFloatRange.hpp"
#include "FFrameRate.hpp"
#include "FGameNameRedirect.hpp"
#include "FLinearColor.hpp"
#include "FNetDriverDefinition.hpp"
#include "FPluginRedirect.hpp"
#include "FSoftClassPath.hpp"
#include "FSoftObjectPath.hpp"
#include "FStatColorMapping.hpp"
#include "FStructRedirect.hpp"
#include "UAssetManager.hpp"
#include "UClass.hpp"
#include "UEngine.hpp"
#include "UEngineCustomTimeStep.hpp"
#include "UFont.hpp"
#include "UGameUserSettings.hpp"
#include "UGameViewportClient.hpp"
#include "UMaterial.hpp"
#include "UMaterialInstanceDynamic.hpp"
#include "UObject.hpp"
#include "UPhysicalMaterial.hpp"
#include "UTexture.hpp"
#include "UTexture2D.hpp"
#include "UTimecodeProvider.hpp"
UEngine* UEngine::StaticClass() {
    static auto res = find_uobject("Class /Script/Engine.Engine");
    return (UEngine*)res;
}
