#pragma once
#include <cstdint>
#include "ECreaturePregnancyState.hpp"
#include "ENotificationCategory.hpp"
#include "FGearItem.hpp"
#include "FGearTraitRecipeData.hpp"
#include "FGeometry.hpp"
#include "FTimespan.hpp"
#include "FTransfigurationUnlockSource.hpp"
#include "FVector2D.hpp"
#include "UBlueprintFunctionLibrary.hpp"
class ACharacter;
class UObject;
class UWidget;
class UCreatureDefinition;
class APhoenixHUD;
class APlayerController;
class AHUD;
class UCreatureState;
class AActor;
class ACameraStackActor;
class UCreatureManager;
class UCameraStackTarget;
class UPhoenixTextBlock;
#pragma pack(push, 1)
class UFL_NurturingFunctionLibary_C : public UBlueprintFunctionLibrary {
public:
    static UFL_NurturingFunctionLibary_C* StaticClass();
    static void GetAllAvailableTraitsForLoom(FGearItem GearItem, FName GearRarity, UObject* __WorldContext, int32_t& TotalAvailableTraits, FName ActiveTraitName, int32_t AvailableTraitsCounter, int32_t Temp_int_Array_Index_Variable, FName CallFunc_Array_Get_Item, int32_t CallFunc_Array_Length_ReturnValue, bool CallFunc_Greater_IntInt_ReturnValue, int32_t Temp_int_Loop_Counter_Variable, int32_t CallFunc_Add_IntInt_ReturnValue, int32_t Temp_int_Array_Index_Variable_1, int32_t Temp_int_Variable, int32_t Temp_int_Loop_Counter_Variable_1, int32_t Temp_int_Loop_Counter_Variable_2, int32_t CallFunc_Add_IntInt_ReturnValue_1, int32_t CallFunc_Add_IntInt_ReturnValue_2, int32_t Temp_int_Array_Index_Variable_2, int32_t Temp_int_Variable_1, bool CallFunc_EqualEqual_NameName_ReturnValue, bool CallFunc_NotEqual_NameName_ReturnValue, TArray<FGearTraitRecipeData>& CallFunc_GetGearTraitRecipes_AllRecipes, int32_t CallFunc_Add_IntInt_ReturnValue_3, FGearTraitRecipeData CallFunc_Array_Get_Item_1, int32_t CallFunc_Array_Length_ReturnValue_1, bool CallFunc_Less_IntInt_ReturnValue, bool CallFunc_NotEqual_NameName_ReturnValue_1, bool CallFunc_NotEqual_NameName_ReturnValue_2, bool CallFunc_BooleanAND_ReturnValue, bool CallFunc_BooleanAND_ReturnValue_1, bool CallFunc_BooleanAND_ReturnValue_2, int32_t CallFunc_Add_IntInt_ReturnValue_4, int32_t Temp_int_Variable_2, TArray<FGearTraitRecipeData>& CallFunc_GetGearTraitRecipes_AllRecipes_1, FGearTraitRecipeData CallFunc_Array_Get_Item_2, int32_t CallFunc_Array_Length_ReturnValue_2, bool CallFunc_Less_IntInt_ReturnValue_1, bool CallFunc_NotEqual_NameName_ReturnValue_3, bool CallFunc_NotEqual_NameName_ReturnValue_4, bool CallFunc_BooleanAND_ReturnValue_3, bool CallFunc_BooleanAND_ReturnValue_4, bool CallFunc_BooleanAND_ReturnValue_5, int32_t CallFunc_Add_IntInt_ReturnValue_5, TArray<FGearTraitRecipeData>& CallFunc_GetGearTraitRecipes_AllRecipes_2, int32_t CallFunc_Array_Length_ReturnValue_3, FGearTraitRecipeData CallFunc_Array_Get_Item_3, bool CallFunc_Less_IntInt_ReturnValue_2, bool CallFunc_NotEqual_NameName_ReturnValue_5, bool CallFunc_NotEqual_NameName_ReturnValue_6, bool CallFunc_BooleanAND_ReturnValue_6, bool CallFunc_BooleanAND_ReturnValue_7, bool CallFunc_BooleanAND_ReturnValue_8);
    static void MoveCursorToCenterOfWidget(UWidget* Widget, UObject* __WorldContext, APlayerController* CallFunc_GetOwningPlayer_ReturnValue, bool CallFunc_IsValid_ReturnValue, FVector2D CallFunc_GetViewportSize_ReturnValue, FGeometry CallFunc_GetCachedGeometry_ReturnValue, FVector2D CallFunc_LocalToViewport_PixelPosition, FVector2D CallFunc_LocalToViewport_ViewportPosition, FVector2D CallFunc_GetAbsoluteSize_ReturnValue, float CallFunc_BreakVector2D_X, float CallFunc_BreakVector2D_Y, FVector2D CallFunc_MakeVector2D_ReturnValue, FVector2D K2Node_MathExpression_ReturnValue, float CallFunc_BreakVector2D_X_1, float CallFunc_BreakVector2D_Y_1);
    static void GetTotalAvailableTriats(FGearItem GearItem, UObject* __WorldContext, int32_t& TotalAvailableTraits, FName ActiveTraitName, int32_t AvailableTraitsCounter, int32_t Temp_int_Loop_Counter_Variable, int32_t CallFunc_Add_IntInt_ReturnValue, FName CallFunc_Array_Get_Item, int32_t CallFunc_Array_Length_ReturnValue, bool CallFunc_Greater_IntInt_ReturnValue, FName CallFunc_GetRarityFromGearItemID_ReturnValue, TArray<FGearTraitRecipeData>& CallFunc_GetGearTraitRecipes_AllRecipes, int32_t CallFunc_Array_Length_ReturnValue_1, bool CallFunc_Less_IntInt_ReturnValue, int32_t Temp_int_Array_Index_Variable, FGearTraitRecipeData CallFunc_Array_Get_Item_1, bool CallFunc_NotEqual_NameName_ReturnValue, bool CallFunc_NotEqual_NameName_ReturnValue_1, bool CallFunc_BooleanAND_ReturnValue, bool CallFunc_BooleanAND_ReturnValue_1, int32_t Temp_int_Variable, bool CallFunc_BooleanAND_ReturnValue_2, int32_t CallFunc_Add_IntInt_ReturnValue_1);
    static void ToggleHideHUDForNurturingScreen(bool Hide, UObject* Provider, UObject* __WorldContext, TArray<ENotificationCategory> NotificationCategories, TArray<FString> HUDElementsToHide, TArray<FString>& K2Node_MakeArray_Array, APlayerController* CallFunc_GetPlayerController_ReturnValue, bool CallFunc_IsValid_ReturnValue, AHUD* CallFunc_GetHUD_ReturnValue, APhoenixHUD* K2Node_DynamicCast_AsPhoenix_HUD, bool K2Node_DynamicCast_bSuccess, TArray<ENotificationCategory>& K2Node_MakeArray_Array_1);
    static void Get_Creature_Pregnancy_Durations(UCreatureState* CreatureState, UObject* __WorldContext, FTimespan& TotalDuration, FTimespan& DurationRemaining, FTimespan CallFunc_MakeTimespan_ReturnValue, FTimespan CallFunc_GetHatchingTimeRemaining_ReturnValue, FTimespan CallFunc_GetGestationTimeRemaining_ReturnValue, ECreaturePregnancyState CallFunc_GetPregnancyState_ReturnValue, UCreatureDefinition* CallFunc_GetDefinition_ReturnValue, bool K2Node_SwitchEnum_CmpSuccess, FTimespan CallFunc_GetPregnancyDuration_ReturnValue, FTimespan CallFunc_GetHatchingDuration_ReturnValue, bool CallFunc_IsEggLaying_ReturnValue, FTimespan CallFunc_Add_TimespanTimespan_ReturnValue, FTimespan CallFunc_Add_TimespanTimespan_ReturnValue_1, bool Temp_bool_Variable, bool Temp_bool_Variable_1, FTimespan K2Node_Select_Default, FTimespan K2Node_Select_Default_1);
    static void GetIsUsingPlayerCamera(UObject* __WorldContext, bool& UsingPlayerCamera, ACharacter* CallFunc_GetPlayerCharacter_ReturnValue, APlayerController* CallFunc_GetPlayerController_ReturnValue, AActor* CallFunc_GetViewTarget_ReturnValue, ACameraStackActor* K2Node_DynamicCast_AsCamera_Stack_Actor, bool K2Node_DynamicCast_bSuccess, UCameraStackTarget* CallFunc_GetTarget_ReturnValue, AActor* CallFunc_GetTargetActor_ReturnValue, bool CallFunc_EqualEqual_ObjectObject_ReturnValue);
    static void Get_Can_View_Creature_Details(UCreatureState* CreatureState, UObject* __WorldContext, bool& CanMoveCreature, FString& ErrorMsgKey, bool CallFunc_IsUnbornCreature_ReturnValue);
    static void Get_Can_Summon_Creature(UCreatureState* CreatureState, UObject* __WorldContext, bool& CanMoveCreature, FString& ErrorMsgKey, ECreaturePregnancyState CallFunc_GetPregnancyState_ReturnValue, UCreatureDefinition* CallFunc_GetDefinition_ReturnValue, bool CallFunc_NotEqual_ByteByte_ReturnValue, bool CallFunc_IsEgg_ReturnValue, bool CallFunc_IsUnbornCreature_ReturnValue);
    static void GetTimeRemainingText(FTimespan TimeRemaining, UObject* __WorldContext);
    static void GetCreatureDisplayNameFromUIDName(FName CreatureUID, UObject* __WorldContext, FString& OutName, bool& OutIsLocalizationKey, UCreatureManager* CallFunc_Get_ReturnValue, UCreatureState* CallFunc_BP_GetCreatureStateByFName_ReturnValue, FString CallFunc_GetCreatureDisplayName_OutName, bool CallFunc_GetCreatureDisplayName_OutIsLocalizationKey, bool CallFunc_IsValid_ReturnValue);
    static void GetCanMoveCreatureOutOfNurtureSpace(UCreatureState* CreatureState, UObject* __WorldContext, bool& CanMoveCreature, FString& ErrorMsgKey, ECreaturePregnancyState CallFunc_GetPregnancyState_ReturnValue, UCreatureDefinition* CallFunc_GetDefinition_ReturnValue, bool CallFunc_NotEqual_ByteByte_ReturnValue, bool CallFunc_IsEgg_ReturnValue, bool CallFunc_IsUnbornCreature_ReturnValue);
    static void GetUnlockTextFromUnlockSource(FTransfigurationUnlockSource Unlock_Source, UObject* __WorldContext);
    static void GetUnbornCreatureIconTextureName(UCreatureDefinition* CreatureDefinition, UObject* __WorldContext, FString& IconTextureName, bool Temp_bool_Variable, bool CallFunc_IsEggLaying_ReturnValue, FName CallFunc_GetEggTypeID_ReturnValue, FName CallFunc_GetOffspringCreatureTypeID_ReturnValue, FName K2Node_Select_Default, FString CallFunc_Conv_NameToString_ReturnValue, FString CallFunc_Concat_StrStr_ReturnValue);
    static void SetTextToCreatureName(UCreatureState* CreatureState, UPhoenixTextBlock* PhoenixTextBlock, UObject* __WorldContext, bool CallFunc_IsValid_ReturnValue, FString CallFunc_GetCreatureDisplayName_OutName, bool CallFunc_GetCreatureDisplayName_OutIsLocalizationKey);
    static void GetCreatureIconTextureName(UCreatureState* CreatureState, UObject* __WorldContext, FString& IconTextureName, bool CallFunc_IsValid_ReturnValue, FString CallFunc_GetIconString_ReturnValue);
    static void GetCreatureInventoryInfoString(FName InVariation, UObject* __WorldContext, FString& OutInfoString, FString InfoString, UCreatureManager* CallFunc_Get_ReturnValue, FString CallFunc_Concat_StrStr_ReturnValue, FString CallFunc_Concat_StrStr_ReturnValue_1, FString CallFunc_Concat_StrStr_ReturnValue_2, UCreatureManager* CallFunc_Get_ReturnValue_1, UCreatureState* CallFunc_BP_GetCreatureStateByFName_ReturnValue, bool CallFunc_GetIsMale_ReturnValue, bool CallFunc_IsValid_ReturnValue, FName CallFunc_GetTypeID_ReturnValue, UCreatureDefinition* CallFunc_BP_GetCreatureDefinitionByType_ReturnValue, bool CallFunc_IsOffspring_ReturnValue);
    static void GetCreatureInventoryButtonLegend(UObject* __WorldContext);
    static void GetCreatureSpecies(FName InCreatureUID, UObject* __WorldContext, FString& CreatureSpecies, UCreatureManager* CallFunc_Get_ReturnValue, UCreatureState* CallFunc_BP_GetCreatureStateByFName_ReturnValue, FName CallFunc_GetTypeID_ReturnValue, bool CallFunc_IsValid_ReturnValue, FString CallFunc_Conv_NameToString_ReturnValue, FString CallFunc_LeftChop_ReturnValue, bool CallFunc_Contains_ReturnValue);
}; // Size: 0x28
#pragma pack(pop)
