#include "EBlendMode.hpp"
#include "EBlendableLocation.hpp"
#include "EDecalBlendMode.hpp"
#include "EMaterialDecalResponse.hpp"
#include "EMaterialDomain.hpp"
#include "EMaterialShadingModel.hpp"
#include "EMaterialShadingRate.hpp"
#include "EMaterialStencilCompare.hpp"
#include "EMaterialTessellationMode.hpp"
#include "ERefractionMode.hpp"
#include "ETranslucencyLightingMode.hpp"
#include "FColorMaterialInput.hpp"
#include "FGuid.hpp"
#include "FLinearColor.hpp"
#include "FMaterialAttributesInput.hpp"
#include "FMaterialCachedExpressionData.hpp"
#include "FMaterialShadingModelField.hpp"
#include "FScalarMaterialInput.hpp"
#include "FShadingModelMaterialInput.hpp"
#include "FVector2MaterialInput.hpp"
#include "FVectorMaterialInput.hpp"
#include "UMaterial.hpp"
#include "UMaterialInterface.hpp"
#include "UPhysicalMaterial.hpp"
#include "UPhysicalMaterialMask.hpp"
UMaterial* UMaterial::StaticClass() {
    static auto res = find_uobject("Class /Script/Engine.Material");
    return (UMaterial*)res;
}
